name: "Setup anchor-cli"
description: "Setup bun and anchor cli"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/cache@v4
      name: Cache Anchor CLI
      id: cache-anchor
      with:
        path: ~/.cargo/bin/anchor
        key: anchor-cli-${{ runner.os }}-${{ env.ANCHOR_CLI_VERSION }}
    - name: Install Anchor CLI
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v${{ env.ANCHOR_CLI_VERSION }} --locked
      shell: bash
