[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.10"
package_manager = "bun"

[workspace]
members = ["programs/farming"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
farming = "FarmuwXPWXvefWUeqFAa5w6rifLkq5X6E8bimYvrhCB1"

[hooks]
