[workspace]
members = ["programs/*", "cli/*"]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "1.0.2" }
anchor-spl = { version = "1.0.2" }
anchor-client = { version = "1.0.2" }
ruint = "1.12"

[profile.release]
overflow-checks = true

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }

[workspace.metadata.cli]
solana = "3.1.10"
